// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDeTn8LFpYBh1jBecqYKBOjVgZiA9HXho',
    appId: '1:776509224127:web:6623ccaee9415b5ef6420a',
    messagingSenderId: '776509224127',
    projectId: 'mi-restaurante-app-bdfbe',
    authDomain: 'mi-restaurante-app-bdfbe.firebaseapp.com',
    storageBucket: 'mi-restaurante-app-bdfbe.firebasestorage.app',
    measurementId: 'G-MZKB0ZKVYT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb3-pB5jj-44CdqcUHts9iMKDt5fs6cQQ',
    appId: '1:776509224127:android:b2d0480440633620f6420a',
    messagingSenderId: '776509224127',
    projectId: 'mi-restaurante-app-bdfbe',
    storageBucket: 'mi-restaurante-app-bdfbe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvKW79KBYe5WKnFAvVxp-NHdzYJ23kro0',
    appId: '1:776509224127:ios:0e88702c877e1956f6420a',
    messagingSenderId: '776509224127',
    projectId: 'mi-restaurante-app-bdfbe',
    storageBucket: 'mi-restaurante-app-bdfbe.firebasestorage.app',
    iosBundleId: 'com.example.meserapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvKW79KBYe5WKnFAvVxp-NHdzYJ23kro0',
    appId: '1:776509224127:ios:0e88702c877e1956f6420a',
    messagingSenderId: '776509224127',
    projectId: 'mi-restaurante-app-bdfbe',
    storageBucket: 'mi-restaurante-app-bdfbe.firebasestorage.app',
    iosBundleId: 'com.example.meserapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDeTn8LFpYBh1jBecqYKBOjVgZiA9HXho',
    appId: '1:776509224127:web:42927af167b80ebff6420a',
    messagingSenderId: '776509224127',
    projectId: 'mi-restaurante-app-bdfbe',
    authDomain: 'mi-restaurante-app-bdfbe.firebaseapp.com',
    storageBucket: 'mi-restaurante-app-bdfbe.firebasestorage.app',
    measurementId: 'G-ZBTJ6M3YLL',
  );
}
